# DATABASE
DATABASE_URL="postgresql://postgres:PASSWORD@localhost:5432/mydb?schema=schema"
DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA



# AUTH.JS SECRET
AUTH_SECRET="uma_chave_aleatoria_com_32+_caracteres"

# GOOGLE LOGIN
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# SMTP
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=2525
SMTP_USER=""
SMTP_PASS=""

TURNSTILE_SECRET_KEY=xxxx
TURNSTILE_SITE_KEY=xxxx

# BASE URL
NEXT_PUBLIC_BASE_URL="http://localhost:3000"


